### ISSUE TITLE
Version 1.1.4 (1.20.1) causing ticking entity for Ender Dragon on servers

### ISSUE THREAD

**Issue by gamerpotion** [masik16u/Mythic-Charms#23]
Hi, we are using Mythic charms in my modpack (DarkRPG) and version 1.1.2 ran fine, but the latest release 1.1.4 seems to be causing ticking error for ender dragon. See below

![image](https://github.com/user-attachments/assets/498ce0ee-c88e-4a70-97bb-8d7c25717f01)

```java.util.NoSuchElementException
    at java.base/java.util.ArrayList$Itr.next(ArrayList.java:970)
    at net.minecraft.class_1510.mixinextras$bridge$next$53(class_1510.java)
    at net.minecraft.class_1510.wrapOperation$eag000$mythic_charms$mountainsStrengthEffectDragon(class_1510.java:1535)
    at net.minecraft.class_1510.method_6825(class_1510.java:440)
    at net.minecraft.class_1510.method_6007(class_1510.java:339)
    at net.minecraft.class_1309.method_5773(class_1309.java:2419)
    at net.minecraft.class_1308.method_5773(class_1308.java:351)
    at net.minecraft.class_3218.method_18762(class_3218.java:739)
    at net.minecraft.class_1937.mixinextras$bridge$accept$190(class_1937.java)
    at com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92)
    at net.minecraft.class_1937.wrapOperation$edj000$neruina$catchTickingEntities$notTheCauseOfTickLag(class_1937.java:11048)
    at net.minecraft.class_1937.method_18472(class_1937.java:480)
    at net.minecraft.class_3218.method_31420(class_3218.java:385)
    at net.minecraft.class_5574.method_31791(class_5574.java:54)
    at net.minecraft.class_3218.method_18765(class_3218.java:353)
    at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
    at net.minecraft.class_3176.method_3813(class_3176.java:283)
    at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
    at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
    at java.base/java.lang.Thread.run(Thread.java:840)```

**Comment by masik16u** [comment]
Just uploaded a new version that should potentially fix this

**Comment by masik16u** [comment]
Please let me know if that solved the problem
